name: CodeQL

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbedos/mbed-os-env:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "cpp"
          queries: "+security-and-quality"
          
      - name: Compile NRF52840_DK 
        run:
            mbed test -t GCC_ARM -m NRF52840_DK --compile
      - name: Compile DISCO_L475VG_IOT01A 
        run:            
            mbed test -t GCC_ARM -m DISCO_L475VG_IOT01A --compile
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1
